[package]
name = "cairodeepdive2"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
cairo_execute = "2.12.2"

[cairo]
enable-gas = false

[dev-dependencies]
cairo_test = "2.12.2"

[[target.executable]]
name = "main"
function = "cairodeepdive2::main"



