[package]
name = "staking_contract"
version = "0.1.0"
edition = "2023_01"

[dependencies]
starknet = "2.8.4"
openzeppelin = "0.20.0"

[[target.starknet-contract]]
sierra = true
casm = true

[tool.snforgery]
exit-first = true